---
- name: Install and configure MySQL
  hosts: localhost
  gather_facts: True
  roles:
    - role: mysql
      tags:
        - db

- name: Get additional packages
  hosts: localhost
  gather_facts: True
  roles:
    - role: packages
      tags:
        - pkg

- name: Install nextcloud
  hosts: localhost
  gather_facts: False
  roles:
    - role: nextcloud
      tags:
        - nextcloud

- name: Copy mysql.ini and nextcloud.conf files over
  hosts: localhost
  gather_facts: False
  roles:
    - role: file_xfer
      tags:
        - config

- name: Configure apache and postfix
  hosts: localhost
  gather_facts: False
  roles:
    - role: apache_postfix
      tags:
        - appost

- name: Install and Enable Redis PHP module
  hosts: localhost
  gather_facts: False
  roles:
    - role: redis
      tags:
        - redistag
